package kp.ran.higherorderexamples



/// data class example
data class Student(val name: String, val age: Int, val grade: Char)

fun main() {
    // Creating an instance of the data class
    val student1 = Student("John", 18, 'A')

    // Accessing properties
    println("Name: ${student1.name}, Age: ${student1.age}, Grade: ${student1.grade}")

    // Using toString() generated by the data class
    println("Student1: $student1")

    // Creating a copy with modified values
    val student2 = student1.copy(name = "Jane", grade = 'B')
    println("Student2: $student2")

    // Using destructuring declaration to extract values
    val (a, b, c) = student1
    println("Destructured: $a, $b, $c")

    // Using equals() generated by the data class
    val student3 = Student("John", 18, 'B')
    println("Are student1 and student3 equal? ${student1 == student3}")
}

